# Build Steps:
steps:

#
# Steps for building and testing vertx-template with Oracle DB
#

- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', "apt-get update; apt-get install curl -y; curl 'http://metadata.google.internal/computeMetadata/v1/project/' -H 'Metadata-Flavor: Google'"]
